### ISSUE TITLE
[Urgent] Join function is not working for new users

### ISSUE THREAD

**Issue by orz9** [study-buddy-developers/study-buddy#17]
Join function seems to hang when new user is trying to press the button. The testing video is attached here.

Such problem do not occur to existing users.

https://user-images.githubusercontent.com/40697164/191049998-e81a3e57-c4f9-4abd-b051-dd71b44730a8.mp4

**Comment by joshuan98** [comment]
Some session had "pax" field empty. Session removed and check correct
