### ISSUE TITLE
Data storing/retrieving function is buggy

### ISSUE THREAD

**Issue by orz9** [study-buddy-developers/study-buddy#20]
When returned user click "Done" in order to skip the "modify saved data" question, the bot skips the rest of the questions and jump straight to create the study session.

**Expected program flow**
1. User login
2. Program asks for modification.
3. If no modification requires to be made by user, the program skips the questions that have existing data stored, and **still ask for the rest of the questions**.
4. If user wants to make changes, they select the option they want to change, the program ask the specific question and overwrite the data stored in the database. Then the program will move on to the rest of the questions which do not have data stored.
5. Program create group message after all questions have been answered.

https://user-images.githubusercontent.com/40697164/191086429-670e5578-b4fa-4de3-ad95-1c1f5742857d.MP4

**Comment by joshuan98** [comment]
Bug found and fixed
